version: '3'
services:
  joomla:
    image: joomla:5.1.beta-php8.2-apache
    container_name: feym_joomla
    ports:
      - 8080:80
    volumes:
      - ./joomla:/var/www/html
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_NAME: joomla
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: Test1!
    depends_on:
      - db
  drupal:
    image: drupal
    container_name: feym_drupal
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: Test1!
      MYSQL_DATABASE: drupal
      MYSQL_USER: root
      MYSQL_PASSWORD: Test1!
    depends_on:
      - db
  wordpress:
    image: wordpress
    container_name: feym_wordpress
    ports:
      - 8082:80
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
  web:
    build: .
    container_name: feym_webserver
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html
  db:
    image: mysql
    container_name: feym_mysql
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Test1!
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: feym_phpmyadmin
    ports:
      - 8084:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: Test1!
    depends_on:
      - db
