version: '3'
services:
  web:
    build: .
    container_name: ls_webserver
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html
  db:
    image: postgres
    container_name: ls_postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD_USER: Test!
  phpmyadmin:
    image: dpage/pgadmin4
    container_name: ls_pgadmin
    ports:
      - 8084:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: Test1!
    depends_on:
      - db
