version: '3'
services:
  wordpress:
    image: wordpress
    container_name: ls_wordpress
    ports:
      - 8082:80
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
  web:
    build: .
    container_name: ls_webserver
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Test1!
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ls_phpmyadmin
    ports:
      - 8084:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: Test1!
    depends_on:
      - db
